import os
from dotenv import load_dotenv
load_dotenv()
SECRET_KEY = os.getenv("SECRET_KEY")
ALGORITHM = "HS256"
ACCESS_TOKEN_EXPIRE_MINUTES = int(os.getenv("ACCESS_TOKEN_EXPIRE_MINUTES", "60"))
DATABASE_URL = os.getenv("DATABASE_URL")
DATABASE_URL_MASTER = os.getenv("DATABASE_URL_MASTER")
DATABASE_URL_SLAVE = os.getenv("DATABASE_URL_SLAVE") 
#print(SECRET_KEY)
#print(DATABASE_URL)
#print(DATABASE_URL_MASTER, DATABASE_URL_SLAVE)